workspace:
  base: /app
  path: src/github.com/high-value-team/totalorder

pipeline:

  backend_build:
    image: library/mono
    commands:
      - mkdir -p /app/src/github.com/high-value-team/totalorder/backend/bin/app
      - cp /app/src/github.com/high-value-team/totalorder/backend/build/template.docker.Dockerfile /app/src/github.com/high-value-team/totalorder/backend/bin/Dockerfile
      - cd /app/src/github.com/high-value-team/totalorder/backend/src/to.backend
      - nuget restore
      - msbuild /p:OutDir=/app/src/github.com/high-value-team/totalorder/backend/bin/app totalorder.sln

  backend_docker:
    debug: true
    image: plugins/docker
    repo: hvt1/totalorder-backend
    secrets: [ docker_username, docker_password ]
    context: /app/src/github.com/high-value-team/totalorder/backend/bin
    dockerfile: /app/src/github.com/high-value-team/totalorder/backend/bin/Dockerfile

  frontend_build:
    image: node
    commands:
      - cd /app/src/github.com/high-value-team/totalorder/frontend/build
      - yarn install
      - npx run build_for_drone

  frontend_docker:
    debug: true
    image: plugins/docker
    repo: hvt1/totalorder-frontend
    secrets: [ docker_username, docker_password ]
    context: /app/src/github.com/high-value-team/totalorder/frontend/bin
    dockerfile: /app/src/github.com/high-value-team/totalorder/frontend/bin/Dockerfile

  frontend_rancher:
    image: peloton/drone-rancher
    url: http://hvt.zone:8080/v1
    service: totalorder/frontend
    docker_image: hvt1/totalorder-frontend
    secrets: [ rancher_access_key, rancher_secret_key ]
    confirm: true
    timeout: 180

  backend_rancher:
    image: peloton/drone-rancher
    url: http://hvt.zone:8080/v1
    service: totalorder/backend
    docker_image: hvt1/totalorder-backend
    secrets: [ rancher_access_key, rancher_secret_key ]
    confirm: true
    timeout: 180


